# Generated by Django 3.0.6 on 2020-05-10 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0002_auto_20200510_1633'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GameImage',
            new_name='ConsoleImage',
        ),
    ]
