# Generated by Django 3.0.6 on 2020-05-15 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_revieweditems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='age_limit',
            field=models.CharField(blank=True, max_length=999),
        ),
        migrations.AlterField(
            model_name='revieweditems',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product'),
        ),
    ]
