# Generated by Django 3.0.6 on 2020-05-15 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='step',
            field=models.CharField(default='billing', max_length=255),
        ),
    ]
