# Generated by Django 3.0.6 on 2020-05-15 17:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0004_auto_20200515_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='billinginfo',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='billinginfo',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
