# Generated by Django 3.0.6 on 2020-05-15 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_paymentinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinfo',
            name='card_number',
            field=models.DecimalField(decimal_places=0, max_digits=19),
        ),
    ]
