# Generated by Django 3.0.6 on 2020-05-15 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_auto_20200515_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='payment.PaymentInfo'),
        ),
    ]
