# Generated by Django 3.0.6 on 2020-05-15 21:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_order_payment_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinfo',
            name='card_number',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(16), django.core.validators.MaxValueValidator(19)]),
        ),
    ]
