# Generated by Django 3.0.6 on 2020-05-15 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0010_auto_20200515_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinfo',
            name='card_number',
            field=models.DecimalField(decimal_places=0, max_digits=16),
        ),
    ]
